server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TCenkErguven/Java7ConfigServerGit.git
          default-label: main
          skip-ssl-validation: true
          username: TCenkErguven
          password: ${configGitPass}