server:
  port: 8090

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socialmediaDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

my-application:
  jwt:
    secretkey: ${secretkey}
    audience: ${audience}
    issuer: ${issuer}

rabbitmq:
  queueRegister: register-queue